### ISSUE TITLE
Need README file

### ISSUE THREAD

**Issue by ALLINONE4298** [ALLINONE4298/Competitive-Coding-Solutions#26]
Need README.md file in simple array sum problem in Hacker Rank directory,
1) Create new README.md file with problem question
2) Nothing should be missing from question. (while copying some of the text left as unselected or can't be copied)
3) File should be proper formatted as original at hacker rank or have a look at other problem README files to get an idea.

Note:
Use # and ### for heading and sub-heading.
Use * for bullet points.
Use two spaces for line break or leave a single line to make another paragraph.

**Comment by sickmick69** [comment]
Kindly assign the issue @ALLINONE4298

**Comment by Suraj13s** [comment]
Kindly assign the issue @ALLINONE4298
